[dockerfiles]
python = "./docker/Dockerfile.python"
javascript = "./docker/Dockerfile.javascript"
java = "./docker/Dockerfile.java"

[paths]
tar_path = "./docker/context/"

[constants]
dockerfile = "Dockerfile"
docker_created_by_label = "created_by"
service_name = "REXEC"
executor_container_name = "executor_container"
executor_image_name = "executor:latest"
tar_file_name = "context.tar"

[build]
service_port = 50051
grpc_ui_port = 50052
service_name = "REXEC"
